#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class DupPlugin < Nagios::Plugin

  plugin do |plug|
    plug.status = :ok
    plug.output = 'not really; will fail'
  end

  plugin do |plug|
    plug.status = :ok
    plug.output = 'not really; will fail'
  end
end

plugin = DupPlugin.new
plugin.exec!
