#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MarkerFilePlugin

  include Naplug

  plugin do |p|

    if Time.now - File.mtime(p[:marker_file]) > p[:critical]
      p.status.critical!
      p.output! "marker file #{p[:marker_file]} mtime greater than #{p[:critical]} seconds"
    else
      p.status.ok!
      p.output! "marker #{p[:marker_file]} is up to date"
    end

  end
end

plugin = MarkerFilePlugin.new :marker_file => '/tmp/my_marker', :critical => 120
plugin.exec!
