#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MarkerFilePlugin < Nagios::Plugin

  plugin do |plug|
    if Time.now - File.mtime(plug.args[:marker_file]) > plug.args[:critical]
      plug.status = :critical
      plug.output = 'marker mtime greater than 60 seconds'
    else
      plug.status = :ok
      plug.output = 'marker up to date'
    end
  end
end

plugin = MarkerFilePlugin.new :marker_file => '/tmp/my_marker', :critical => 120
plugin.exec!
