#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MarkerFilePlugin < Nagios::Plugin

  plugin do |args|
    result = Result.new
    if Time.now - File.mtime(args[:marker_file]) > args[:critical]
      result.status = :critical
      result.output = 'marker mtime greater than 60 seconds'
    else
      result.status = :ok
      result.output = 'marker up to date'
    end
    result
  end
end

plugin = MarkerFilePlugin.new :marker_file => '/tmp/my_marker', :critical => 120
plugin.exec
puts plugin.single_line_output
exit plugin.exit_code
