#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MarkerFilePlugin



  plugin do |plug|
    begin
      delta = Time.now - File.mtime(plug[:marker_file])
      plug.output = 'marker file is %d seconds out of date' % [delta]
      case
        when delta < plug.args[:w_seconds]
          plug.status = :ok
          plug.output = 'marker file %s is up to date' % [plug.args[:marker_file]]
        when (plug.args[:w_seconds]..plug.args[:c_seconds]).include?(delta)
          plug.status = :warning
        when delta >= plug.args[:c_seconds]
          plug.status = :critical
      end
    rescue Errno::ENOENT => e
      plug.status = :unknown
      plug.output = 'marker file %s does not exist' % [plug.args[:marker_file]]
      plug.payload = e
    end
  end
end

plugin = MarkerFilePlugin.new :marker_file => '/tmp/my_marker', :c_seconds => 120, :w_seconds => 60
plugin.exec!
