#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MultiPluginPlugin

  include Naplug

  plugin :one do |p|

    plugin :p1 do |p1|
      p1.status.ok!
      p1.output! "#{p.tag}:#{p1.tag} #{p[:instance]}"
    end

    plugin :p2 do |p2|
      p2.status.ok!
      p2.output! "#{p.tag}:#{p2.tag} #{p[:instance]}"
    end

    plugin :p3 do |p3|
      p3.status.ok!
      p3.output! "#{p.tag}:#{p3.tag} #{p[:instance]}"
    end

  end

  plugin :two do |p|

    p.status.ok!
    p.output! "plugin #{p.tag}"

  end

end


x1 = MultiPluginPlugin.new :instance => :x1, :one => { :p1 => { :instance => :x1 }}
x2 = MultiPluginPlugin.new :instance => :x2, :one => { :p1 => { :instance => :x2 }}
x1.exec!
