#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MultiPlugPlugin

  include Naplug

  plugin do |p|

    plug :p1 do |p1|
      p1.status.critical!
      p1.output! "'c' argument is #{p1[:c]}"
    end

    plug :p2 do |p2|
      p2.status.critical!
      p2.output! "tis critical!"
    end

    plug :p3 do |p3|
      p3.status.warning!
      p3.output! "tis unknown!"
    end
  end

end

plugin = MultiPlugPlugin.new :shared1 => 'shared arg2', :shared2 => 'shared arg 2', :p1 => { :c => 0 }
plugin.exec!
