#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require 'rubygems'
require 'naplug'

class MultiPlugin < Nagios::Plugin

  plugin :p1 do |plug|
    plug.status = :ok
    plug.output = "#{plug.tag} args: #{plug.args}"
  end

  plugin :p2 do |plug|
    plug.status = :ok
    plug.output = "#{plug.tag} args: #{plug.args}"
  end
end

plugin = MultiPlugin.new :shared1 => 'shared arg2', :shared2 => 'shared arg 2', :p1 => { :c => 0 }
plugin.exec!
